import { config } from 'dotenv-flow'

config()

export default {
    // SERVER
    ENV: process.env.ENV,
    PORT: process.env.PORT,
    SERVER_URL: process.env.SERVER_URL,
    FRONTEND_URL: process.env.FRONTEND_URL,

    // DATABASE
    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_NAME: process.env.DATABASE_NAME,

    // APPLICATION
    JWT_TOKEN_SECRET: process.env.JWT_TOKEN_SECRET,
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: process.env.JWT_REFRESH_TOKEN_EXPIRATION_TIME,

    // RATE_LIMITING
    POINTS_PER_SECOND: process.env.POINTS_PER_SECOND,
    DURATION: process.env.DURATION,

    // NODE_MAILER
    MAILER_SECURE: process.env.NODE_MAILER_SECURE,
    MAILER_PORT: process.env.NODE_MAILER_PORT,
    MAILER_USER: process.env.NODE_MAILER_USER,
    MAILER_PASSWORD: process.env.NODE_MAILER_PASS,

    // OTHERS
    ADMIN_EMAIL: process.env.ADMIN_EMAIL,
    REDIS_HOST: process.env.REDIS_HOST,
    REDIS_PORT: process.env.REDIS_PORT,
    COST_PER_CALLERID_CHECK: process.env.COST_PER_CALLERID_CHECK,
    COST_PER_CALLERID_FETCH: process.env.COST_PER_CALLERID_FETCH,
    TIME_TO_UPDATE_DB_BY_REDIS: process.env.TIME_TO_UPDATE_DB_BY_REDIS,
    GEOLOCATION_API_URL: process.env.GEOLOCATION_API_URL,
    TIME_TO_UPDATE_LOG: process.env.TIME_TO_UPDATE_LOG,
    DEFAULT_BANK_ICON_WIDTH: process.env.DEFAULT_BANK_ICON_WIDTH || 30,
    DEFAULT_BANK_ICON_HEIGHT: process.env.DEFAULT_BANK_ICON_HEIGHT || 30,

    // ADMIN SETTINGS

    // ?? USER

    IS_REGISTRATION_ENABLE: process.env.IS_REGISTRATION_ENABLE,
    PASSWORD_POLICY: (process.env.PASSWORD_POLICY as 'basic' | 'medium' | 'strong') || 'medium',
    SESSION_TIMEOUT: process.env.SESSION_TIMEOUT,
    MAX_LOGIN_ATTEMPTS: process.env.MAX_LOGIN_ATTEMPTS,
    MAX_WITHDRAW: process.env.MAX_WITHDRAW, // Pending
    MAX_DEPOSITS: process.env.MAX_DEPOSITS, // Pending
    MAX_FILES: process.env.MAX_FILES,

    // ?? TRANSACTION
    TRANSACTION_FEE_IN_PERCENT: process.env.TRANSACTION_FEE_IN_PERCENT,

    // ??
    DATA_RETENTION_PERIOD: process.env.DATA_RETENTION_PERIOD
}
